### PR TITLE
Port to Python3 and fix scripts.

### PR DESCRIPTION
**Pull request by nevsan**

### CODE REVIEW

**Comment by cmars** [comment]
@nevsan Thanks for this. I've added you as a collaborator on the project.

**Comment by nevsan** [comment]
@cmars Do you plan to update the version hosted on PyPi?

**Comment by cmars** [comment]
@nevsan I would, but I've lost my PyPI account username and password it's been so long, and I don't see a password reset.

**Comment by nevsan** [comment]
Does this help? https://pypi.python.org/pypi?%3Aaction=forgotten_password_form

The only reason I ask is that our Continuous Integration setup runs faster when we install packages from PyPi vs. from source.

**Comment by cmars** [comment]
@nevsan Thanks, I've got it back. What's your PyPI ID? I'll add you to the project if you like.

**Comment by nevsan** [comment]
I am also `nevsan` on PyPi.

**Comment by cmars** [comment]
Done.

**Pull request merged**
